# Generated by Django 4.1.10 on 2023-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
